### ISSUE TITLE
 បា issue

### ISSUE THREAD

**Issue by ttolaaa** [panhavad/unicode-to-limon-shortcut#1]
ba is having issue, when ba is present it should be replace with )a.
Some application does not have issue with ba but some application like CAPCUT, it was having this issue.
ba was looking ha, but testing with )a is working better.

**Comment by panhavad** [comment]
Understood the issue, trying to test with CAPCUT. Getting this issue.
ba
![image](https://github.com/panhavad/unicode-to-limon-shortcut/assets/7156904/46e82062-6a30-4e49-a03b-ba1c128d981c)
b a
![image](https://github.com/panhavad/unicode-to-limon-shortcut/assets/7156904/a564d1cf-7fc2-4d19-911d-e31e18b1a18d)
)a
![image](https://github.com/panhavad/unicode-to-limon-shortcut/assets/7156904/ec00ed12-1c17-43e1-8d14-89a9b52789fe)
) a
![image](https://github.com/panhavad/unicode-to-limon-shortcut/assets/7156904/4ae740bd-40d0-4979-b1e4-2416e3dc5ae4)

Understood the issue, fixing in the next commit.
